name: model-supervisé RL
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python A57_rl_tp.py
          # Write your CML report
          echo "## Metriques:" >> report.md
          cat metrics.txt >> report.md
          git config --global user.email "wassilachamekh.alg@gmail.com"
          git config --global user.name "wassila"
          git add report.md metrics.txt
          git commit -m "pousser vers github repository"
          git push origin HEAD:master
